name: pets
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  

  supabase_flutter: ^2.5.6
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  uuid: ^4.5.1
  timeago: ^3.6.0
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.68.0
  meta: ^1.12.0

  flutter_markdown: ^0.6.22
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
